# Generated by Django 3.0.3 on 2020-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(default='', max_length=32, verbose_name='简历名称'),
        ),
    ]
