# Generated by Django 3.0.3 on 2020-04-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200417_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_name',
            field=models.CharField(max_length=32, verbose_name='简历名称'),
        ),
    ]
