# Generated by Django 3.0.3 on 2020-04-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200419_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunterposition',
            name='resume_id',
            field=models.OneToOneField(default='2', on_delete=django.db.models.deletion.CASCADE, to='backend.Resume'),
        ),
    ]
