# Generated by Django 3.0.3 on 2020-04-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_hunterposition_resume_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hunterposition',
            old_name='resume_id',
            new_name='resume',
        ),
    ]
