# Generated by Django 3.0.3 on 2020-04-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200419_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterposition',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Resume'),
        ),
    ]
