# Generated by Django 3.0.3 on 2020-04-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200419_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterposition',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='申请职位时间'),
        ),
    ]
