# Generated by Django 3.0.3 on 2020-04-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200419_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hunterposition',
            old_name='interview_id',
            new_name='interview',
        ),
        migrations.AlterField(
            model_name='interview',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='面试时间'),
        ),
    ]
