# Generated by Django 3.0.3 on 2020-04-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200420_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterposition',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Resume'),
        ),
    ]
