# Generated by Django 3.0.3 on 2020-04-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200420_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterposition',
            name='resume',
            field=models.CharField(max_length=32, null=True, verbose_name='投递简历'),
        ),
    ]
