# Generated by Django 3.0.3 on 2020-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200421_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='1', max_length=2, verbose_name='用户类型'),
        ),
    ]
