# Generated by Django 3.0.5 on 2020-05-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_position_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyresume',
            name='collect_time',
            field=models.DateField(null=True, verbose_name='收藏时间'),
        ),
        migrations.AddField(
            model_name='hunterposition',
            name='collect_time',
            field=models.DateField(null=True, verbose_name='收藏时间'),
        ),
    ]
