# Generated by Django 2.2.12 on 2020-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200505_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=200, verbose_name='公司介绍'),
        ),
    ]
