# Generated by Django 2.2.12 on 2020-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20200508_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='temp',
            field=models.CharField(default='temp1', max_length=32, verbose_name='模板'),
        ),
    ]
