# Generated by Django 2.2.12 on 2020-05-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_resume_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyresume',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='发送面试邀请时间'),
        ),
    ]
