# Generated by Django 2.2.12 on 2020-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(default='0', max_length=10, verbose_name='状态'),
        ),
    ]
