# Generated by Django 2.2.12 on 2020-05-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200520_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(default='0', max_length=1, verbose_name='状态'),
        ),
    ]
