# Generated by Django 2.2.12 on 2020-05-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20200520_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(max_length=800, verbose_name='职位描述'),
        ),
    ]
