# Generated by Django 2.2.12 on 2020-05-30 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20200524_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='release_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
