# Generated by Django 2.2.12 on 2020-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20200530_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='内容'),
        ),
    ]
